services:
  - type: web
    name: sweetwater-stock-checker
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      npx playwright install chromium --with-deps --force
    startCommand: gunicorn app:app
