services:
  - type: web
    name: sweetwater-stock-checker
    env: python
   buildCommand: |
  pip install -r requirements.txt
  python -m playwright install chromium
    startCommand: gunicorn app:app
    plan: free
