services:
  - type: web
    name: sweetwater-stock-checker
    env: python
    buildCommand: |
      pip install -r requirements.txt
      npx playwright install chromium --with-deps
    startCommand: gunicorn app:app
    plan: free
