services:
  - type: web
    name: sweetwater-stock-checker
    env: python
    buildCommand: |
      pip install -r requirements.txt
      npx playwright install chromium
    startCommand: gunicorn app:app
    envVars:
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /opt/render/.cache/ms-playwright
